version: "3.8"
services:  # Here I define the services that should get vstarted with the compose file
  web:  # First is the "web" service
    build: ./frontend # its built from the dockerfile in ./frontend 
    depends_on: # "web" depends on "api"
      - api
    ports: # portmapping host:container
      - "3000:3000"
    networks: # connected to network "backend"
      - network-backend
  api:  # second service is "api"
    build: ./backend # gets built from dockerfile in ./backend
    depends_on: # dependant on mongo
      - mongo
    ports: # portmapping host:container
      - "3001:3001"
    networks: # connected to network "backend"
     - network-backend
  
  mongo:
    image: mongo
    restart: always # restarts service when it gets stopped suddenly (not manually)
    volumes: # defines volume
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username #setting env. variables
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    ports: # portmapping host:container
     - 27017:27017
    networks: 
     - network-backend  # connected to network "backend"

networks: # network creation
  network-backend:

volumes: # volume creation
  mongodb_data:
